REASON_CATEGORIES = ("FMS_DETECTED", "CUSTOMER_COMPLAINT", "OTHER_BFI_INFO")
SUSPICION_TYPES = ("MONEY_MULE", "SOCIAL_ENGINEERING", "ECONOMIC_SABOTAGE", "OTHER")
DISPUTE_STATUS = ("PENDING_HOLD", "HELD", "RELEASED", "ESCALATED", "WRITTEN_OFF")
VERIFICATION_EVENT_TYPES = (
    "INITIATED",
    "CUSTOMER_CONTACTED",
    "CUSTOMER_RESPONSE",
    "OTHER_BFI_CONTACTED",
    "OTHER_BFI_RESPONSE",
    "BSP_QUERY",
    "FUNDS_RELEASED",
    "FUNDS_RESTITUTED",
    "ESCALATED_TO_LEA",
)
FLAG_SOURCES = ("RULE_ENGINE", "MANUAL_ANALYST", "OTHER_BFI", "LAW_ENFORCEMENT")
